"""initial inventory schema

Revision ID: 50f995297bfe
Revises: 
Create Date: 2026-08-05 13:54:09.447869
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '50f995297bfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('metadata_uri', sa.Text(), nullable=True),
    sa.Column('feature_schema', sa.JSON(), nullable=True),
    sa.Column('training_dataset', sa.Text(), nullable=True),
    sa.Column('training_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_artifacts_name_version')
    )
    op.create_index(op.f('ix_model_artifacts_is_active'), 'model_artifacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_artifacts_model_name'), 'model_artifacts', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_artifacts_model_type'), 'model_artifacts', ['model_type'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('recommended_order_quantity', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('risk_color', sa.String(length=16), nullable=True),
    sa.Column('demand_pattern', sa.String(length=32), nullable=False),
    sa.Column('demand_source', sa.String(length=32), nullable=False),
    sa.Column('forecast_source', sa.String(length=32), nullable=False),
    sa.Column('forecast_method', sa.String(length=64), nullable=False),
    sa.Column('routing_reason', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('service_level', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('lead_time_demand', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('safety_stock_method', sa.String(length=32), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('inventory_gap', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('p50', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('p90', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('forecast_daily', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('current_stock >= 0', name='ck_analysis_runs_current_stock_non_negative'),
    sa.CheckConstraint('recommended_order_quantity >= 0', name='ck_analysis_runs_recommended_order_non_negative'),
    sa.CheckConstraint('service_level > 0 and service_level < 1', name='ck_analysis_runs_service_level_range'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_analysis_runs_request_id')
    )
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_risk'), 'analysis_runs', ['risk'], unique=False)
    op.create_index(op.f('ix_analysis_runs_sku_code'), 'analysis_runs', ['sku_code'], unique=False)
    op.create_index(op.f('ix_analysis_runs_sku_id'), 'analysis_runs', ['sku_id'], unique=False)
    op.create_table('forecast_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_artifact_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=True),
    sa.Column('demand_class', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('evaluation_scope', sa.String(length=32), nullable=False),
    sa.Column('metric_mae', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('metric_rmse', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('metric_bias', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('metric_wape', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('metric_mase', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('n_skus', sa.Integer(), nullable=True),
    sa.Column('n_test_points', sa.Integer(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifacts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_evaluations_demand_class'), 'forecast_evaluations', ['demand_class'], unique=False)
    op.create_index(op.f('ix_forecast_evaluations_evaluation_scope'), 'forecast_evaluations', ['evaluation_scope'], unique=False)
    op.create_index(op.f('ix_forecast_evaluations_generated_at'), 'forecast_evaluations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_forecast_evaluations_model_artifact_id'), 'forecast_evaluations', ['model_artifact_id'], unique=False)
    op.create_index(op.f('ix_forecast_evaluations_model_name'), 'forecast_evaluations', ['model_name'], unique=False)
    op.create_index(op.f('ix_forecast_evaluations_sku_id'), 'forecast_evaluations', ['sku_id'], unique=False)
    op.create_table('inventory_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('service_level', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('moq', sa.Integer(), server_default='1', nullable=False),
    sa.Column('order_multiple', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_order_quantity', sa.Integer(), nullable=True),
    sa.Column('holding_cost_per_unit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stockout_cost_per_unit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('holding_cost_per_unit is null or holding_cost_per_unit >= 0', name='ck_inventory_policies_holding_cost_non_negative'),
    sa.CheckConstraint('lead_time_days between 1 and 365', name='ck_inventory_policies_lead_time_range'),
    sa.CheckConstraint('max_order_quantity is null or max_order_quantity > 0', name='ck_inventory_policies_max_order_positive'),
    sa.CheckConstraint('moq >= 0', name='ck_inventory_policies_moq_non_negative'),
    sa.CheckConstraint('order_multiple >= 1', name='ck_inventory_policies_order_multiple_positive'),
    sa.CheckConstraint('service_level > 0 and service_level < 1', name='ck_inventory_policies_service_level_range'),
    sa.CheckConstraint('stockout_cost_per_unit is null or stockout_cost_per_unit >= 0', name='ck_inventory_policies_stockout_cost_non_negative'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_policies_is_active'), 'inventory_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_policies_sku_id'), 'inventory_policies', ['sku_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_available >= 0', name='ck_stock_levels_available_non_negative'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_stock_levels_on_hand_non_negative'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_stock_levels_reserved_non_negative'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_levels_recorded_at'), 'stock_levels', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_stock_levels_sku_id'), 'stock_levels', ['sku_id'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('target_start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('demand_source', sa.String(length=32), nullable=False),
    sa.Column('forecast_method', sa.String(length=64), nullable=False),
    sa.Column('forecast_source', sa.String(length=32), nullable=False),
    sa.Column('routing_reason', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('model_artifact_id', sa.Integer(), nullable=True),
    sa.Column('input_history_length', sa.Integer(), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('p50', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('p90', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('forecast_daily', sa.JSON(), nullable=True),
    sa.Column('recommended_order_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_observed_demand', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('actual_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('actual_observed_demand is null or actual_observed_demand >= 0', name='ck_prediction_logs_actual_non_negative'),
    sa.CheckConstraint('forecast_horizon_days > 0', name='ck_prediction_logs_horizon_positive'),
    sa.CheckConstraint('input_history_length >= 0', name='ck_prediction_logs_history_length_non_negative'),
    sa.CheckConstraint('recommended_order_quantity >= 0', name='ck_prediction_logs_recommended_order_non_negative'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifacts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_analysis_run_id'), 'prediction_logs', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_forecast_method'), 'prediction_logs', ['forecast_method'], unique=False)
    op.create_index(op.f('ix_prediction_logs_model_artifact_id'), 'prediction_logs', ['model_artifact_id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_predicted_at'), 'prediction_logs', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_prediction_logs_sku_code'), 'prediction_logs', ['sku_code'], unique=False)
    op.create_index(op.f('ix_prediction_logs_sku_id'), 'prediction_logs', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_logs_sku_id'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_sku_code'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_predicted_at'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_model_artifact_id'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_forecast_method'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_analysis_run_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_stock_levels_sku_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_recorded_at'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_inventory_policies_sku_id'), table_name='inventory_policies')
    op.drop_index(op.f('ix_inventory_policies_is_active'), table_name='inventory_policies')
    op.drop_table('inventory_policies')
    op.drop_index(op.f('ix_forecast_evaluations_sku_id'), table_name='forecast_evaluations')
    op.drop_index(op.f('ix_forecast_evaluations_model_name'), table_name='forecast_evaluations')
    op.drop_index(op.f('ix_forecast_evaluations_model_artifact_id'), table_name='forecast_evaluations')
    op.drop_index(op.f('ix_forecast_evaluations_generated_at'), table_name='forecast_evaluations')
    op.drop_index(op.f('ix_forecast_evaluations_evaluation_scope'), table_name='forecast_evaluations')
    op.drop_index(op.f('ix_forecast_evaluations_demand_class'), table_name='forecast_evaluations')
    op.drop_table('forecast_evaluations')
    op.drop_index(op.f('ix_analysis_runs_sku_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_sku_code'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_risk'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('skus')
    op.drop_index(op.f('ix_model_artifacts_model_type'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_model_name'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_is_active'), table_name='model_artifacts')
    op.drop_table('model_artifacts')
    # ### end Alembic commands ###

